language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 1.9.3
before_script:
  - cd spec/dummy
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rails s &
  - cd ../..
script: ./travis.sh
notifications:
  email: false
  webhooks: 
    secure: "LB5lA5zXMHlbPl2ItQ3BWeFgrLg6x02tHRhrHyjeKCIrcXuwky4RqRHbZJu2Yl+OUATER/+6qkUecr7HVHQKujipQHkqHT+JbT+AprE3LyLjdMTZKchpG5w6zTR4QASydne0beLhzmg+b8jI3fUWtqhEllL2sCrNkNHnAo6f00o="